main:
  params: [input]
  steps:
    - init:
        assign:
          - jobId: ${input.jobId}
          - requestId: ${input.requestId}
          - datasetVersion: ${input.datasetVersion}
          - modelVersion: ${input.modelVersion}
    - preprocess:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT") + "/locations/" + sys.get_env("GOOGLE_CLOUD_REGION") + "/jobs/ei-preprocess-job:run"}
          auth:
            type: OAuth2
          body:
            overrides:
              containerOverrides:
                - args: ["--datasetVersion", ${datasetVersion}]
        result: preprocessResult
    - train:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT") + "/locations/" + sys.get_env("GOOGLE_CLOUD_REGION") + "/jobs/ei-train-job:run"}
          auth:
            type: OAuth2
          body:
            overrides:
              containerOverrides:
                - args: ["--datasetVersion", ${datasetVersion}, "--modelVersion", ${modelVersion}]
        result: trainResult
    - inference:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT") + "/locations/" + sys.get_env("GOOGLE_CLOUD_REGION") + "/jobs/ei-inference-job:run"}
          auth:
            type: OAuth2
        result: inferenceResult
    - promote:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT") + "/locations/" + sys.get_env("GOOGLE_CLOUD_REGION") + "/jobs/ei-promote-job:run"}
          auth:
            type: OAuth2
          body:
            overrides:
              containerOverrides:
                - args: ["--modelVersion", ${modelVersion}]
        result: promoteResult
    - done:
        return:
          status: "completed"
          jobId: ${jobId}
          requestId: ${requestId}
